// resources/js/components/FormField.vue
<script setup lang="ts">
import { ref, watch, type PropType } from 'vue';

type FieldType = 'text' | 'email' | 'tel' | 'url' | 'password' | 'number' | 'textarea' | 'select' | 'boolean' | 'checkbox' | 'tags' | 'image' | 'file' | 'color' | 'date' | 'time' | 'datetime' | 'repeater';

interface FieldOption {
    [key: string]: string | { ar: string; en: string };
}

const props = defineProps({
    modelValue: {
        type: [String, Number, Boolean, Array, Object] as PropType<any>,
        default: '',
    },
    type: {
        type: String as PropType<FieldType>,
        default: 'text',
    },
    label: {
        type: String,
        required: true,
    },
    description: {
        type: String,
        default: '',
    },
    placeholder: {
        type: String,
        default: '',
    },
    rules: {
        type: Array as PropType<string[]>,
        default: () => [],
    },
    error: {
        type: String,
        default: '',
    },
    disabled: {
        type: Boolean,
        default: false,
    },
    required: {
        type: Boolean,
        default: false,
    },
    options: {
        type: [Array, Object] as PropType<FieldOption | string[]>,
        default: () => [],
    },
    min: {
        type: [Number, String],
        default: null,
    },
    max: {
        type: [Number, String],
        default: null,
    },
    step: {
        type: [Number, String],
        default: 1,
    },
    rows: {
        type: Number,
        default: 3,
    },
    accept: {
        type: String,
        default: '',
    },
    icon: {
        type: String,
        default: '',
    },
    prepend: {
        type: String,
        default: '',
    },
    append: {
        type: String,
        default: '',
    },
    searchable: {
        type: Boolean,
        default: false,
    },
    monospace: {
        type: Boolean,
        default: false,
    },
});

const emit = defineEmits<{
    (e: 'update:modelValue', value: any): void;
    (e: 'fileChange', file: File): void;
}>();

const localValue = ref<any>(props.modelValue);

watch(() => props.modelValue, (newValue) => {
    localValue.value = newValue;
});

watch(localValue, (newValue) => {
    emit('update:modelValue', newValue);
});

const isRequired = props.rules?.includes('required') || props.required;

const getOptionLabel = (option: string | { ar: string; en: string }, value: string): string => {
    if (typeof option === 'object') {
        return option.ar || option.en || value;
    }
    return option;
};
</script>

<template>
    <div class="form-group mb-4">
        <!-- Label -->
        <label v-if="label" class="form-label d-block mb-2">
            <span v-if="icon" :class="icon" class="me-2"></span>
            {{ label }}
            <span v-if="isRequired" class="text-danger">*</span>
        </label>

        <!-- Description -->
        <p v-if="description" class="text-muted small mb-2">{{ description }}</p>

        <!-- Text Input -->
        <template v-if="['text', 'email', 'tel', 'url', 'password'].includes(type)">
            <div class="input-group">
                <span v-if="prepend" class="input-group-text">{{ prepend }}</span>
                <input :type="type" v-model="localValue" :placeholder="placeholder" :disabled="disabled" :min="min"
                    :max="max" :step="step" class="form-control" :class="{ 'is-invalid': error }" />
                <span v-if="append" class="input-group-text">{{ append }}</span>
            </div>
        </template>

        <!-- Number Input -->
        <template v-else-if="type === 'number'">
            <input type="number" v-model="localValue" :placeholder="placeholder" :disabled="disabled" :min="min"
                :max="max" :step="step" class="form-control" :class="{ 'is-invalid': error }" />
        </template>

        <!-- Textarea -->
        <template v-else-if="type === 'textarea'">
            <textarea v-model="localValue" :placeholder="placeholder" :disabled="disabled" :rows="rows"
                class="form-control" :class="{ 'is-invalid': error, 'font-monospace': monospace }"></textarea>
        </template>

        <!-- Select -->
        <template v-else-if="type === 'select'">
            <select v-model="localValue" :disabled="disabled" class="form-select" :class="{ 'is-invalid': error }">
                <option value="">{{ placeholder || 'Select...' }}</option>
                <option v-for="(optionLabel, optionValue) in options" :key="optionValue" :value="optionValue">
                    {{ getOptionLabel(optionLabel as any, optionValue as string) }}
                </option>
            </select>
        </template>

        <!-- Boolean/Checkbox -->
        <template v-else-if="['boolean', 'checkbox'].includes(type)">
            <div class="form-check">
                <input type="checkbox" v-model="localValue" :disabled="disabled" class="form-check-input"
                    :class="{ 'is-invalid': error }" />
                <label class="form-check-label">{{ label }}</label>
            </div>
        </template>

        <!-- Tags Input -->
        <template v-else-if="type === 'tags'">
            <input type="text" v-model="localValue" :placeholder="placeholder" :disabled="disabled" class="form-control"
                :class="{ 'is-invalid': error }" />
            <small class="text-muted">Separate tags with commas</small>
        </template>

        <!-- Image/File Upload -->
        <template v-else-if="['image', 'file'].includes(type)">
            <input type="file" :accept="accept || (type === 'image' ? 'image/*' : '')" :disabled="disabled"
                class="form-control" :class="{ 'is-invalid': error }"
                @change="emit('fileChange', ($event.target as HTMLInputElement).files?.[0])" />
            <small v-if="accept || type === 'image'" class="text-muted">
                {{ accept || 'Image files only' }}
            </small>
        </template>

        <!-- Color Picker -->
        <template v-else-if="type === 'color'">
            <input type="color" v-model="localValue" :disabled="disabled" class="form-control form-control-color"
                :class="{ 'is-invalid': error }" />
        </template>

        <!-- Date -->
        <template v-else-if="type === 'date'">
            <input type="date" v-model="localValue" :disabled="disabled" class="form-control"
                :class="{ 'is-invalid': error }" />
        </template>

        <!-- Time -->
        <template v-else-if="type === 'time'">
            <input type="time" v-model="localValue" :disabled="disabled" class="form-control"
                :class="{ 'is-invalid': error }" />
        </template>

        <!-- DateTime -->
        <template v-else-if="type === 'datetime'">
            <input type="datetime-local" v-model="localValue" :disabled="disabled" class="form-control"
                :class="{ 'is-invalid': error }" />
        </template>

        <!-- Error Message -->
        <div v-if="error" class="invalid-feedback d-block">
            {{ error }}
        </div>
    </div>
</template>

<style scoped>
.font-monospace {
    font-family: 'Courier New', Courier, monospace;
}
</style>

// resources/js/react/components/FormField.tsx
import React, { useState, useEffect, ChangeEvent } from 'react';

export interface FormFieldProps {
    value: any;
    onChange: (value: any) => void;
    type?: string;
    label: string;
    description?: string;
    placeholder?: string;
    rules?: string[];
    error?: string;
    disabled?: boolean;
    required?: boolean;
    options?: Record<string, string | { ar: string; en: string }>;
    min?: number | string;
    max?: number | string;
    step?: number | string;
    rows?: number;
    accept?: string;
    icon?: string;
    prepend?: string;
    append?: string;
    searchable?: boolean;
    monospace?: boolean;
}

export const FormField: React.FC<FormFieldProps> = ({
    value,
    onChange,
    type = 'text',
    label,
    description = '',
    placeholder = '',
    rules = [],
    error = '',
    disabled = false,
    required = false,
    options = {},
    min,
    max,
    step = 1,
    rows = 3,
    accept = '',
    icon = '',
    prepend = '',
    append = '',
    searchable = false,
    monospace = false,
}) => {
    const [localValue, setLocalValue] = useState(value);

    useEffect(() => {
        setLocalValue(value);
    }, [value]);

    const handleChange = (newValue: any) => {
        setLocalValue(newValue);
        onChange(newValue);
    };

    const isRequired = rules.includes('required') || required;

    const getOptionLabel = (option: string | { ar: string; en: string }, val: string): string => {
        if (typeof option === 'object') {
            return option.ar || option.en || val;
        }
        return option;
    };

    const renderInput = () => {
        const baseProps = {
            disabled,
            className: `form-control ${error ? 'is-invalid' : ''}`,
        };

        switch (type) {
            case 'text':
            case 'email':
            case 'tel':
            case 'url':
            case 'password':
                return (
                    <div className="input-group">
                        {prepend && <span className="input-group-text">{prepend}</span>}
                        <input
                            type={type}
                            value={localValue || ''}
                            onChange={(e) => handleChange(e.target.value)}
                            placeholder={placeholder}
                            min={min as string | number}
                            max={max as string | number}
                            step={step as number}
                            {...baseProps}
                        />
                        {append && <span className="input-group-text">{append}</span>}
                    </div>
                );

            case 'number':
                return (
                    <input
                        type="number"
                        value={localValue || ''}
                        onChange={(e) => handleChange(parseFloat(e.target.value))}
                        placeholder={placeholder}
                        min={min as number}
                        max={max as number}
                        step={step as number}
                        {...baseProps}
                    />
                );

            case 'textarea':
                return (
                    <textarea
                        value={localValue || ''}
                        onChange={(e) => handleChange(e.target.value)}
                        placeholder={placeholder}
                        disabled={disabled}
                        rows={rows}
                        className={`form-control ${monospace ? 'font-monospace' : ''} ${error ? 'is-invalid' : ''}`}
                    />
                );

            case 'select':
                return (
                    <select
                        value={localValue || ''}
                        onChange={(e) => handleChange(e.target.value)}
                        disabled={disabled}
                        className={`form-select ${error ? 'is-invalid' : ''}`}
                    >
                        <option value="">{placeholder || 'Select...'}</option>
                        {Object.entries(options).map(([optionValue, optionLabel]) => (
                            <option key={optionValue} value={optionValue}>
                                {getOptionLabel(optionLabel, optionValue)}
                            </option>
                        ))}
                    </select>
                );

            case 'boolean':
            case 'checkbox':
                return (
                    <div className="form-check">
                        <input
                            type="checkbox"
                            checked={!!localValue}
                            onChange={(e) => handleChange(e.target.checked)}
                            disabled={disabled}
                            className="form-check-input"
                        />
                        <label className="form-check-label">{label}</label>
                    </div>
                );

            case 'tags':
                return (
                    <>
                        <input
                            type="text"
                            value={Array.isArray(localValue) ? localValue.join(', ') : localValue}
                            onChange={(e) => handleChange(e.target.value.split(',').map((s: string) => s.trim()))}
                            placeholder={placeholder}
                            disabled={disabled}
                            {...baseProps}
                        />
                        <small className="text-muted">Separate tags with commas</small>
                    </>
                );

            case 'image':
            case 'file':
                return (
                    <>
                        <input
                            type="file"
                            accept={accept || (type === 'image' ? 'image/*' : '')}
                            disabled={disabled}
                            className={`form-control ${error ? 'is-invalid' : ''}`}
                            onChange={(e: ChangeEvent<HTMLInputElement>) => {
                                const file = e.target.files?.[0];
                                if (file) handleChange(file);
                            }}
                        />
                        <small className="text-muted">{accept || 'Image files only'}</small>
                    </>
                );

            case 'color':
                return (
                    <input
                        type="color"
                        value={localValue || '#000000'}
                        onChange={(e) => handleChange(e.target.value)}
                        disabled={disabled}
                        className="form-control form-control-color"
                    />
                );

            case 'date':
                return (
                    <input
                        type="date"
                        value={localValue || ''}
                        onChange={(e) => handleChange(e.target.value)}
                        disabled={disabled}
                        {...baseProps}
                    />
                );

            case 'time':
                return (
                    <input
                        type="time"
                        value={localValue || ''}
                        onChange={(e) => handleChange(e.target.value)}
                        disabled={disabled}
                        {...baseProps}
                    />
                );

            case 'datetime':
                return (
                    <input
                        type="datetime-local"
                        value={localValue || ''}
                        onChange={(e) => handleChange(e.target.value)}
                        disabled={disabled}
                        {...baseProps}
                    />
                );

            default:
                return (
                    <input
                        type="text"
                        value={localValue || ''}
                        onChange={(e) => handleChange(e.target.value)}
                        placeholder={placeholder}
                        disabled={disabled}
                        {...baseProps}
                    />
                );
        }
    };

    return (
        <div className="form-group mb-4">
            {label && (
                <label className="form-label d-block mb-2">
                    {icon && <i className={`${icon} me-2`}></i>}
                    {label}
                    {isRequired && <span className="text-danger"> *</span>}
                </label>
            )}

            {description && <p className="text-muted small mb-2">{description}</p>}

            {renderInput()}

            {error && (
                <div className="invalid-feedback d-block">
                    {error}
                </div>
            )}
        </div>
    );
};

export default FormField;
